site_name: Craftium

docs_dir: craftium-docs

nav:
  - Home: docs/index.md
  - User Guide:
      - docs/installation.md
      - docs/getting-started.md
      - docs/creating-envs.md
  - General Information:
      - Observations and actions: docs/obs-and-acts.md
      - docs/environments.md
      - Wrappers: docs/wrappers.md
  - Misc:
    - docs/troubleshooting.md
    - API Reference: docs/reference.md

theme: readthedocs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

extra:
    version: 0.1
    links:
        - https://github.com/mkdocs
        - https://docs.readthedocs.org/en/latest/builds.html#mkdocs
        - http://www.mkdocs.org/

markdown_extensions:
- admonition