[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "craftium"
version = "0.0.1"
description = "A Gymnasium wrapper for the minetest game engine"
readme = "craftium-readme.md"
license = "LICENSE.txt"
keywords = ["gymnasium", "minetest", "minecraft", "reinforcement learning"]

dependencies = [
    "stable_baselines3",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["craftium"]
